"""Theme research domain models and fixtures."""

from astra.theme_research.contracts import (
    CONTRACT_VERSION,
    CandidateRecallResult,
    CandidateStock,
    EvidenceItem,
    FixtureCompany,
    FixtureThemeDataset,
    FocusCompany,
    NormalizedThemeRequest,
    PipelineStageTrace,
    RecalledCandidate,
    RecallMatch,
    ResearchReport,
    ScoreBreakdown,
    ScoreFactor,
    ThemeResearchError,
    ThemeResearchErrorResponse,
    ThemeResearchRequest,
    ThemeResearchResponse,
    ThemeResearchResult,
)
from astra.theme_research.fixtures import load_low_altitude_economy_fixture
from astra.theme_research.recall import normalize_theme_query, recall_candidates

__all__ = [
    "CONTRACT_VERSION",
    "CandidateStock",
    "CandidateRecallResult",
    "EvidenceItem",
    "FixtureCompany",
    "FixtureThemeDataset",
    "FocusCompany",
    "NormalizedThemeRequest",
    "PipelineStageTrace",
    "RecallMatch",
    "RecalledCandidate",
    "ResearchReport",
    "ScoreBreakdown",
    "ScoreFactor",
    "ThemeResearchError",
    "ThemeResearchErrorResponse",
    "ThemeResearchRequest",
    "ThemeResearchResponse",
    "ThemeResearchResult",
    "load_low_altitude_economy_fixture",
    "normalize_theme_query",
    "recall_candidates",
]
